### ISSUE TITLE
Update names as needed based on CCPPStandardNames repo

### ISSUE THREAD

**Issue by cacraigucar** [ESCOMP/CAM-SIMA#116]
The standard names in the NCAR/CCPPStandardNames repo have been updated to reflect usage by both NOAA and MMM and also to adhere as closely as possible to the CF conventions.  CAMDEN needs to be updated to match.

**Comment by nusbaume** [comment]
This will temporarily be done once ESCOMP/CCPPStandardNames#56 has been merged.  However, given that new physics schemes will occasionally require new standard names forever, and that we have what seems to be a good standard name workflow now, I am going ahead and closing this particular issue.
