### ISSUE TITLE
Include constituent properties in qneg

### ISSUE THREAD

**Issue by peverwhee** [ESCOMP/CAM-SIMA#137]
Currently, qneg_run loops over the entire q array. Need to be able to tell (perhaps at init time?) whether this is correct behavior when qneg is called -> for example, when called from update_state, we do NOT want to iterate through the whole thing.

**Comment by nusbaume** [comment]
@peverwhee Does this issue still need to be resolved?  The qneg physics scheme does use the constituent properties and minimum values field now, but not during the run phase, and it still loops through the entire q array.  Thoughts?

**Comment by nusbaume** [comment]
@peverwhee That sounds like a good plan to me! I'll go ahead and close this issue then.
