### ISSUE TITLE
Need to update NUOPC cap

### ISSUE THREAD

**Issue by nusbaume** [ESCOMP/CAM-SIMA#146]
The NUOPC cap in CAMDEN is currently behind the latest version used in CAM.  Thus the NUOPC code in CAMDEN should be updated and re-tested, so that we know NUOPC still works in CAMDEN, and that it matches CAM.

Also, please note that this issue may require the updating of the CIME, CMEPS, and CDEPS externals as well.

**Comment by peverwhee** [comment]
Notes from #253 review comments:
1. Make sure necessary timing calls are present.
2. Remove comment block ~line 981?
