### ISSUE TITLE
Need ability to link to MICM library at build time

### ISSUE THREAD

**Issue by nusbaume** [ESCOMP/CAM-SIMA#217]
### What is the feature/what would you like to discuss?

CAMDEN needs the ability to link to the Model Independent Chemical Mechanisms (MICM) chemistry package.  

For the MICM-equivalent issue see:  https://github.com/NCAR/musica/issues/21

### Is there anyone in particular you want to be part of this conversation?

@mattldawson

### Will this change (regression test) answers?

No

### Will you be implementing this enhancement yourself?

Any Software Engineer can do this

**Comment by K20shores** [comment]
Closed by #225 225
