### ISSUE TITLE
enter units for physconst fields

### ISSUE THREAD

**Issue by cacraigucar** [ESCOMP/CAM-SIMA#35]
In the file physconst.meta, there are a number of fields which still have the placeholder 'enter units'.  These need replacing with the correct units.

**Comment by nusbaume** [comment]
@cacraigucar I think this is no longer the case, but since you opened the issue I wanted to double-check with you first before closing.  Thanks!

**Comment by peverwhee** [comment]
closing this issue since there are no outstanding units in physconst, but there are a couple that are wrong - https://github.com/ESCOMP/CAM-SIMA/issues/283
